- name: Find existing Disks on Storage Domain
  ovirt_disks_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "storage_domain={{ storage_domain_id }}"

- name: Remove Disks
  ovirt_disks:
    state: absent
    id: "{{ ovirt_item.id }}"
    auth: "{{ ovirt_auth }}"
  with_items: "{{ ovirt_disks }}"
  when:
    - ovirt_item.name != 'OVF_STORE'
    - not hosted_engine or (ovirt_item.id != hosted_engine_vm_disk_id)
  loop_control:
    loop_var: ovirt_item
